FROM golang:alpine as builder

WORKDIR /app

RUN apk update && apk add make

COPY . .

RUN GOOS=linux CGO_ENABLED=0 make build

FROM alpine as runtime

COPY --from=builder /app/go-url-expander /app/go-url-expander

CMD ["/app/go-url-expander"]