name: CI

on: [push, pull_request]

jobs:
    build-image:
      runs-on: ubuntu-latest
      name: build
      steps:
        - uses: actions/checkout@v2
        - name: Setup go
          uses: actions/setup-go@v2
          with:
            go-version: 1.19
        - run: make build-image
    build-image-multistage:
      runs-on: ubuntu-latest
      name: test
      steps:
        - uses: actions/checkout@v2
        - run: make build-image-multi